version: 2

# Build documentation in the docs/ directory
sphinx:
  configuration: docs/conf.py

# Use a Python environment
python:
  version: "3.9"  # Adjust Python version if needed
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
