
# Required
version: 2

# Set the OS, Python version, and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Build documentation with Sphinx
sphinx:
  configuration: source/conf.py

# Optional: Build your docs in additional formats such as PDF
formats:
  - pdf

# Python dependencies
python:
  install:
    - requirements: requirements.txt
